version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: back-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: node index.js
    depends_on:
       - db
    restart: always

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: front-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev
    depends_on: 
      - server

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports: 
      - "3306:3306"
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge

volumes:
  db_data: